### ISSUE TITLE
Publish to Grafana Plugin Library

### ISSUE THREAD

**Issue by KieranWynn** [mullerpeter/databricks-grafana#13]
Thanks for making this @mullerpeter!

Any chance you can publish this plugin to the Grafana plugin library?

I have a self-hosted Grafana instance but I don't have access to the filesystem, so I can't install plugins that way. I do have admin access to the Grafana application, so if I could install via the Grafana UI, that would be amazing! Currently this plugin isn't available when searching in the plugin library. 

Thanks

**Comment by mullerpeter** [comment]
Hi @KieranWynn

Since Grafana offers it's own [Enterprise Databricks Plugin](https://grafana.com/grafana/plugins/grafana-databricks-datasource/), I don't believe they will accept a free version in their plugin library. 

Other open-source versions of Enterprise only Grafana plugins (i.e. Snowflake, MongoDB) also don't appear in the official plugin library and need to be installed manually.
