### ISSUE TITLE
Inquiry as to caching 

### ISSUE THREAD

**Issue by rogerrogeryau** [mullerpeter/databricks-grafana#36]
May I ask whether it supports caching feature like what other grafana built in data sources do?

thanks

**Comment by mullerpeter** [comment]
Hi @rogerrogeryau 

According to the [Grafana Documentation](https://grafana.com/docs/grafana/latest/administration/data-source-management/#data-sources-that-work-with-query-caching) the plugin should support caching as it's extending from the `DataSourceWithBackend` class of the plugin SDK. (Looks like caching is not a feature the plugin developer has to actively implement)

Since the caching feature seems to be only available on the Enterprise version, which I don't have at hand, you would need to check yourself to be 100% certain. If there is a cache tab in the plugin settings, then the plugin supports caching.
